markers: 
  - {id: 1, frame_id: "map", pose: {x: 3.00, y: 0.902, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 2, frame_id: "map", pose: {x: 10.05, y: 0.902, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 3, frame_id: "map", pose: {x: 12.30, y: 1.00, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 4, frame_id: "map", pose: {x: 10.35, y: 3.00, z: 0.28, roll: 0.0, pitch: 0.0, yaw: -1.57}}